### ISSUE TITLE
[Bug report]

### ISSUE THREAD

**Issue by logslmao** [CleanroomMC/Multiblocked#100]
#### Multiblocked version:
0.5.3

#### Forge version:
14.23.5.2859-2860 (both have the same result

#### Singleplayer or Multiplayer:
Single Player

#### Installed mods:
Brandon's Core 2.4.20.22, 2.7.3 Beta GregtechCEu, Draconic Evolution 2.3.28.193

## Link to full crash-report or log
https://pastebin.com/MMNp1xJW

#### How to reproduce:
I seriously dont know what to type here, if i launch it it just crashed immediatley

#### Expected result:
it launches

#### Actual result:
it crashed

#### Pictures:
no pictures

**Comment by Rongmario** [comment]
Install MixinBooter
