### ISSUE TITLE
[Bug report] Crashes on servers (1.12)

### ISSUE THREAD

**Issue by CalaMariGold** [CleanroomMC/Multiblocked#101]
#### Multiblocked version:
0.7.2

#### Forge version:
14.23.5.2860

#### Singleplayer or Multiplayer:
Multiplayer

#### Installed mods:
Multiblocked and mixinbooter 7.0

## Link to full crash-report or log
https://mclo.gs/fbLu4rX

#### Actual result:
Crashes servers

**Comment by Nrmot** [comment]
Update multiblocked to latest version, and try again

**Comment by CalaMariGold** [comment]
Fixed, thanks!
