### ISSUE TITLE
[Bug report] Multiblock machines negative time remaining

### ISSUE THREAD

**Issue by DiegoRutolo** [CleanroomMC/Multiblocked#104]
#### Multiblocked version:
1.0.10

#### Forge version:
40.2.17

#### Singleplayer or Multiplayer:
Singleplayer

#### Installed mods:
[Multiblock Madness 2](https://github.com/Filostorm/Multiblock-Madness-2)

#### How to reproduce:
When a multiblock machine loses power, the time remaining can go into negatives, and when it gets power againg, the number keeps decreasing, consuming power but never finishing.

#### Expected result:
When a machine loses power it should stop progress, not go into negative numbers.

#### Actual result:
The process never finishes.

#### Pictures:
![2024-05-27_21 47 49](https://github.com/CleanroomMC/Multiblocked/assets/32809544/6e7cbd77-250e-49f0-9fd2-51115202f12c)

**Comment by friendlyhj** [comment]
Wrong repo. 1.16.5+ go here https://github.com/Low-Drag-MC/Multiblocked
