### ISSUE TITLE
lighting issues

### ISSUE THREAD

**Issue by TheNelston** [CleanroomMC/Multiblocked#13]
non-full blocks, when used as either geckolib or blockstate models, will cause lighting issues (the block is completely dark). not sure if this is due to lighting changes via mods (e.g: phosphor) or not, could be a potential issue for modpack compatibility

**Comment by Yefancy** [comment]
Set the block non opaque in the editor

**Comment by TheNelston** [comment]
im actually so stupid, thank you!
