### ISSUE TITLE
On some game loads I can't open any worlds

### ISSUE THREAD

**Issue by Filostorm** [CleanroomMC/Multiblocked#34]
Super vague I know, but I can't reproduce it on demand. This is the third time its happened since I've been using MBD.

[Crash Report](https://github.com/CleanroomMC/Multiblocked/files/8609848/crash-2022-05-03_06.15.33-server.txt)
[latest.log](https://github.com/CleanroomMC/Multiblocked/files/8609849/latest.log)

**Comment by Yefancy** [comment]
#35

**Comment by Filostorm** [comment]
Yep, same issue
