### ISSUE TITLE
Saves being randomly corrupted since adding Multiblocked

### ISSUE THREAD

**Issue by Deiwos** [CleanroomMC/Multiblocked#35]
Version: Multiblocked 0.5.3

Since I've been using Multiblocked I've been noticing saves becoming 'corrupted' several times now, and I've needed to restore from backups. I've been working on this project for months and this has never happened before.

Each time it happens, the following crash reports occur. The first report is the first time loading the save after it's 'corrupted', the second report is what happens on any subsequent attempt to load the save.

https://gist.github.com/Deiwos/b9eaefb33f04337ec3ab38f5433768d5

**Comment by Yefancy** [comment]
I'll be working on fixing these bugs soon

**Comment by Filostorm** [comment]
When it happens for me, I just restart the game, that normally fixes it. No need to restore from backup.

**Comment by Filostorm** [comment]
It also happens when you try to make a new world before restarting the game.

**Comment by Deiwos** [comment]
> When it happens for me, I just restart the game, that normally fixes it. No need to restore from backup.

Did you miss the part where I said 'any subsequent attempt to load the save'?

**Comment by Filostorm** [comment]
Ah, I see.

**Comment by Yefancy** [comment]
I just updated mbd, I am not sure whether 0.5.4 fix this issue. This issue wont be closed atm.

**Comment by Yefancy** [comment]
Does this still happen

**Comment by Deiwos** [comment]
It hasn't happened yet, but gimme about a day to test and I'll see if it does or not.

**Comment by Deiwos** [comment]
It's been a day and I've been doing a bunch of restarts trying to make multiblocks function, and no corruption has occurred.

**Comment by Yefancy** [comment]
ty. glad that this issue doesn't seem to be happening anymore. Reopen it once it happens again.
