### ISSUE TITLE
[Feature Request] "Portals" for modpack authors

### ISSUE THREAD

**Issue by JadianRadiator** [CleanroomMC/Multiblocked#41]
I would like to request support for the ability to teleport players to the specified dimension and coordinates on collision with the player when in the "working" state.
Would ofcourse need to specify said dimmension/coordinates per placed instance of the "portal" multiblock.
I would also like the ability to trigger based on[ ~redstone, or~](https://github.com/CleanroomMC/Multiblocked/issues/4#issuecomment-1110626604) collision with a specified entity (including entities from mods).
If you _do_ add this, I can see people wanting computercraft support.
What I am hoping to do is a static model when "formed",
a seemingly separate object when working and transitioning between "formed" and "working"

1. static, turned off
2. seemingly new object appearing and expanding
3. seemingly new object idling

and the opposite/inverse when turned off or deactivated

**Comment by Yefancy** [comment]
mostly can be done via ct.

**Comment by JadianRadiator** [comment]
Wouldn't using ct make the destination identical across all portals?

**Comment by JadianRadiator** [comment]
came up with a more inclusive way of doing this.
https://github.com/CleanroomMC/Multiblocked/issues/43
