### ISSUE TITLE
[Feature Request] a text input type that zenscript can test for

### ISSUE THREAD

**Issue by JadianRadiator** [CleanroomMC/Multiblocked#43]
I'd like to request a text input type that zenscript can test for.
So that map/modpack makers can use zenscript to make portals, or any other important function unique to each placement.
Plus the ability to detect entity and player collisions.

**Comment by Yefancy** [comment]
What's the text input？

**Comment by JadianRadiator** [comment]
dude,
this is a feature request, not a wiki page.

**Comment by JadianRadiator** [comment]
a zenscript parameter read from the structure in and of itself.
Arbitrarily for the sake of the argument...
structure block A containing the text line "structure_hello=world"
zen script doing "if structure_hello==world then..."

**Comment by Yefancy** [comment]
i see. you mean add text for a predicate of structure pattern. and you can read such info via ct

**Comment by JadianRadiator** [comment]
yes... as long as said text can be different/unique to each placement of the same multiblock.

**Comment by Yefancy** [comment]
there is a new conditon to check blocks in the structure in the latest version (v0.6.2)
