### ISSUE TITLE
Game crash upon mouse click with JEI installed

### ISSUE THREAD

**Issue by m31317015** [CleanroomMC/Multiblocked#47]
Hi, the 1.18.2 game crashed with only Multiblocked, JEI and AE2 installed.

https://pastebin.com/A7r0bwKg

Much appreciated.

**Comment by Yefancy** [comment]
use the JEI with version 9.5.0+

**Comment by m31317015** [comment]
Hi Yefancy, apologies, JEI is on 10.1.0.200, I will use 9.7.0 for now.

**Comment by Yefancy** [comment]
wait, you are using the 10.1.0.200, but it didnt work?

**Comment by m31317015** [comment]
> wait, you are using the 10.1.0.200, but it didnt work?
[crash-2022-06-15_14.35.07-client.txt](https://github.com/CleanroomMC/Multiblocked/files/8906510/crash-2022-06-15_14.35.07-client.txt)

Can confirm it's 10.1.0.200
![image](https://user-images.githubusercontent.com/7257292/173760301-279564c8-5888-428e-a9a1-3e60280661f6.png)

**Comment by Yefancy** [comment]
Try 9.7.0 first. 9.7.0 Try it first. Now, JEI changes the API frequently, which is really annoying

**Comment by m31317015** [comment]
> Try 9.7.0 first. Now, JEI changes the API frequently, which is really annoying

Thanks for your quick response. :)

**Comment by Yefancy** [comment]
btw, 1.16+ issues had better be posted [here](https://github.com/Low-Drag-MC/Multiblocked/issues)

**Comment by Yefancy** [comment]
btw, 1.16+ issues had better be posted [here](https://github.com/Low-Drag-MC/Multiblocked/issues)

**Comment by m31317015** [comment]
> btw, 1.16+ issues had better be posted [here](https://github.com/Low-Drag-MC/Multiblocked/issues)

Understandable, CurseForge brought me here though. :)
