### ISSUE TITLE
NCO/QMD related crash.

### ISSUE THREAD

**Issue by GBLodb** [CleanroomMC/Multiblocked#48]
MBD version: 0.6.1
NCO version: 2o.6.1
QMD version: 1.1-beta5

crash report: https://gist.github.com/GBLodb/2c7fa7cf4c20ca9546eaa97919ce14b6
full debug.log: https://gist.github.com/GBLodb/f8f8833bdef35af1c60f0ed5b9135e26

**Comment by Yefancy** [comment]
#44

https://github.com/Lach01298/QMD/issues/74
