### ISSUE TITLE
[1.18.2] [mekanism gas] [SMP] recipe issue with separate (ore more one) outputs. 

### ISSUE THREAD

**Issue by ptk2003** [CleanroomMC/Multiblocked#54]
if recipe has named outputs slot (like as 'gout1' and 'gout2') multiblock processed recipe but product voided.
structure of multiblock contain 'copability' blocks ("any mekanism gas tank") with set same (as recipe) name slot outputs.

if recipe not set name of outputs, it correct process recipe while outputs have another free space.

example recipe part:
      "outputs": {
        "mek_gas": [
          {
            "content": {
              "type": "mekanism:fissile_fuel",
              "amount": 8000
            },
            "chance": 1.0,
            "slotName": "gout1"
          },
          {
            "content": {
              "type": "mekanism:spent_nuclear_waste",
              "amount": 1000
            },
            "chance": 1.0,
            "slotName": "gout1"
          }
        ]
      }

example structure part:
      "gasout1": {
        "capability": "mek_gas",
        "type": "capability",
        "io": "OUT",
        "slotName": "gout1"
      },
      "gasout2": {
        "capability": "mek_gas",
        "type": "capability",
        "io": "OUT",
        "slotName": "gout2"
      },

forge/1.18.2-40.1.51
Multiblocked-1.18.2-0.10.0
Multiblocked_LowDragLib-1.18.2-0.6.5
Mekanism-1.18.2-10.2.4

**Comment by Rongmario** [comment]
Any issues for Multiblocked on imaginary versions goes to this repository, thank you: https://github.com/Low-Drag-MC/Multiblocked/issues
