### ISSUE TITLE
Recipe questions

### ISSUE THREAD

**Issue by Primitive-Human** [CleanroomMC/Multiblocked#66]
When creating a recipe using the in-game GUI, there are these optional settings at the bottom of the recipe menu, one for a Y level, biome, weather and block. 

The settings for the first three I can understand, yet haven't properly play-tested with yet. But I don't understand what the optional blockstate setting is for. 
Is it meant to only allow certain recipes if the multiblock has a minimum amount of a certain block in its structure? Something like GTCE's coils for the blast furnace? Or is it something else?

**Comment by Yefancy** [comment]
yeah, `if the multiblock has a minimum amount of a certain block in its structure`
