### ISSUE TITLE
Launching detects duplicate mod (when using GDLauncher)

### ISSUE THREAD

**Issue by Vapaman** [CleanroomMC/Multiblocked#7]
Forge version: 14.23.5.2860
Mixinbooter: mixinbooter-4.2
Multiblocked: multiblocked-0.4.0 (file ID: 3758247) (the most recent one, happens with id: 3757892 too)

When trying to launch the game, forge detects a duplicate instance of the mod, crashing the game.

Log:
[latest.log](https://github.com/CleanroomMC/Multiblocked/files/8507798/latest.log)

Screenshot:
![2022-04-18_22 52 36](https://user-images.githubusercontent.com/77460466/163868064-50a3e0ef-5aca-4a48-9677-85cb827077e1.png)

**Comment by Rongmario** [comment]
Similar bug report: https://github.com/gorilla-devs/GDLauncher/issues/1279 , seems to only occur (randomly) with players using GDLauncher.

**Comment by Vapaman** [comment]
https://github.com/FionaTheMortal/better-biome-blend/issues/30

Same issue here. They managed to fix it. Might be worth looking into.

**Comment by Rongmario** [comment]
Thanks, just taken a look but doesn't really help much. Do you have a `debug.log`? It'd offer more information.

**Comment by Vapaman** [comment]
I cant find a debug.log file, but I have a log of the GDlauncher console

[log.txt](https://github.com/CleanroomMC/Multiblocked/files/8514865/log.txt)

**Comment by Rongmario** [comment]
This should be fixed in one of the recent releases. Closing it for now.
