### ISSUE TITLE
Crash when assigning slot names in Recipe Map and Controller Pattern

### ISSUE THREAD

**Issue by michelegargiulo** [CleanroomMC/Multiblocked#71]
Minecraft 1.12.2
Forge: 14.23.5.2860
Multiblocked: 0.8.0a

Setup:
1) Create a new Multiblock with some Item/Fluid/RF Inputs/Outputs
2) Create a new recipe map, set the slotNames on some Inputs/Outputs and assign it to the multiblock
3) Either restart the game or use the Controller Test Block
4) Input some item into the Input "hatches" of the Multiblock
5) The game crashes with the attached crash report

crash report: https://mclo.gs/VglViza

controller: [stb_test01.zip](https://github.com/CleanroomMC/Multiblocked/files/10492581/stb_test01.zip)

recipe map: [test01_rm.zip](https://github.com/CleanroomMC/Multiblocked/files/10492585/test01_rm.zip)

**Comment by Moose1002** [comment]
I'm having this same issue, have you had any luck with solving this?
