### ISSUE TITLE
Minecrafts breaks when reloading with multiblock that has no recipes

### ISSUE THREAD

**Issue by GuineaPigMart** [CleanroomMC/Multiblocked#76]
after i use the command /reload, minecraft stopped working. Serverside stopped happening and i got a really bad memory leak. It started spamming the log like crazy, but Minecraft didn't crash. 

This is on version 1.18

**Comment by Rongmario** [comment]
Report any 1.16+ issues [here](https://github.com/Low-Drag-MC/Multiblocked) instead
