### ISSUE TITLE
[Bug report] Recipes with entity "minecraft:item" do not work. 

### ISSUE THREAD

**Issue by Primitive-Human** [CleanroomMC/Multiblocked#97]
#### Multiblocked version:
0.8.5

#### Forge version:
14.23.5.2860

#### Singleplayer or Multiplayer:
Singleplayer

#### Installed mods:
Bare minimum:
* Minecraft
* Minecraft Forge
* Just Enough Items
* Just Enough Integration
* Mixinbooter 
* Multiblocked 

## Link to full crash-report or log
No crashes, did not observe any errors (physically did not look at the console during this testing)

#### How to reproduce:

1. Create a multiblock that has entities as input or output.
2. Set the entity input or output as "minecraft:item" with NBT "{Item:{id:"minecraft:diamond",Count:1}}" as an example.
3. Testrun the machine to use dropped items as input or spawn dropped items as output.

#### Expected result:
I expect to be able to use dropped items as input entities, or to spawn them as output entities. 
This could make for more immersive multiblocks, like how Botania uses items in-world for its crafting. 
It seems only entity entities are viable, not dropped items. 
To test whether dropped items have additional NBT (dropped by player etc), I used a summon command to spawn the item at the input spot. No success either. 

#### Actual result:
Dropped items are not accepted as input, nor are they spawned as output. 

#### Pictures:
None made.

**Comment by friendlyhj** [comment]
item stack nbt has both damage (type: short) and amount (type: byte). You have to define both their value and type.
`"tag": "{Item:{id:\"minecraft:diamond\",Count:1b,Damage:0s}}"`
