### ISSUE TITLE
CraftTweaker methods for Block Conditions missing on Wiki

### ISSUE THREAD

**Issue by Primitive-Human** [CleanroomMC/Multiblocked#98]
The Block Conditions for Recipes was changed to CraftTweaker conditions a while back.

The wiki shows a few examples for this condition, but not for blocks.

https://github.com/CleanroomMC/Multiblocked/wiki/CraftTweaker-RecipeBuilder#recipe-conditions

I am trying to learn how to use this mod properly (like limiting recipes to number of layer repeats a block has), but I seem to need the block condition for this. 

Last time I touched this feature was in this [post](https://github.com/CleanroomMC/Multiblocked/issues/66#issue-1463888245), but I was unaware of the full switch to CraftTweaker conditions until I tried to use this condition.

**Comment by Rongmario** [comment]
I've appended it to the wiki, thank you for notifying!
